FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web-bff/package.json apps/web-bff/package.json
COPY packages/design-system/package.json packages/design-system/package.json
COPY packages/contracts/package.json packages/contracts/package.json
RUN npm install
COPY . .
RUN npm run build:ds && mkdir -p apps/web-bff/public/design-system && cp -R packages/design-system/dist/. apps/web-bff/public/design-system/
EXPOSE 3001
CMD ["node","apps/web-bff/server/server.js"]
