FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web-bff/package.json apps/web-bff/package.json
COPY packages/design-system/package.json packages/design-system/package.json
COPY packages/contracts/package.json packages/contracts/package.json
RUN npm install
COPY . .
EXPOSE 3000
CMD ["sh","-c","node apps/api/scripts/migrate.js && node apps/api/scripts/seed.js && node apps/api/server/server.js"]
